### ISSUE TITLE
kubectl convert doesn't do its job

### ISSUE THREAD

**Issue by virtualistic** [jamesbuckett/ckad-questions#5]
https://github.com/jamesbuckett/ckad-questions/blob/main/05-ckad-observability-maintenance.md#05-06-convert-manifests-between-different-api-versions
The command `kubectl-convert -f ~/ckad/06-04-beta-ingress.yml --output-version networking.k8s.io/v1`
give us this output:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  creationTimestamp: null
  name: my-ingress
spec:
  rules:
  - http:
      paths:
      - backend: {}
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
```
  
but applying it shows an error: 

`The Ingress "my-ingress" is invalid: spec.rules[0].http.paths[0].backend: Invalid value: "": resource or service backend is required`

So you need to copy/paste from the ingress example the service part so it looks like this:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  creationTimestamp: null
  name: my-ingress
spec:
  rules:
  - http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: my-service 
            port:
              number: 8080 
status:
  loadBalancer: {}
  ```
